version: '3.2'
services:
  hello:
    image: cymin/hello
    container_name: hello
    build:
      context: .
    env_file:
      - hello.env
    ports:
      - ${HELLO_SERVER_PORT:-8080}:8080

networks:
  default:
    external:
      name: service